export declare const DEEPL_LANGS: {
    readonly en: "английский";
    readonly ar: "арабский";
    readonly bg: "болгарский";
    readonly hu: "венгерский";
    readonly el: "греческий";
    readonly da: "датский";
    readonly id: "индонезийский";
    readonly es: "испанский";
    readonly it: "итальянский";
    readonly zh: "китайский";
    readonly ko: "корейский";
    readonly lv: "латышский";
    readonly lt: "литовский";
    readonly de: "немецкий";
    readonly nl: "нидерландский";
    readonly nb: "норвежский";
    readonly pl: "польский";
    readonly pt: "португальский";
    readonly ro: "румынский";
    readonly ru: "русский";
    readonly sk: "словацкий";
    readonly sl: "словенский";
    readonly tr: "турецкий";
    readonly uk: "украинский";
    readonly fi: "финский";
    readonly fr: "французский";
    readonly cs: "чешский";
    readonly sv: "шведский";
    readonly et: "эстонский";
    readonly ja: "японский";
};
export declare const deepl: (text?: string, from?: string, to?: string) => Promise<unknown>;
