export declare const RANKS_BOLD: Readonly<{
    readonly v_1: Path2D;
    readonly v_10: Path2D;
    readonly v_11: Path2D;
    readonly v_12: Path2D;
    readonly v_13: Path2D;
    readonly v_2: Path2D;
    readonly v_3: Path2D;
    readonly v_4: Path2D;
    readonly v_5: Path2D;
    readonly v_6: Path2D;
    readonly v_7: Path2D;
    readonly v_8: Path2D;
    readonly v_9: Path2D;
}>;
export declare const RANKS_THIN: Readonly<{
    readonly v_1: Path2D;
    readonly v_10: Path2D;
    readonly v_11: Path2D;
    readonly v_12: Path2D;
    readonly v_13: Path2D;
    readonly v_2: Path2D;
    readonly v_3: Path2D;
    readonly v_4: Path2D;
    readonly v_5: Path2D;
    readonly v_6: Path2D;
    readonly v_7: Path2D;
    readonly v_8: Path2D;
    readonly v_9: Path2D;
}>;
declare const SUITS_NORMALIZED: {
    readonly rh: Path2D;
    readonly rn: Path2D;
    readonly bh: Path2D;
    readonly bn: Path2D;
};
export { SUITS_NORMALIZED as SUITS };
export declare const RANKS_TYPES: {
    readonly thin: Readonly<{
        readonly v_1: Path2D;
        readonly v_10: Path2D;
        readonly v_11: Path2D;
        readonly v_12: Path2D;
        readonly v_13: Path2D;
        readonly v_2: Path2D;
        readonly v_3: Path2D;
        readonly v_4: Path2D;
        readonly v_5: Path2D;
        readonly v_6: Path2D;
        readonly v_7: Path2D;
        readonly v_8: Path2D;
        readonly v_9: Path2D;
    }>;
    readonly bold: Readonly<{
        readonly v_1: Path2D;
        readonly v_10: Path2D;
        readonly v_11: Path2D;
        readonly v_12: Path2D;
        readonly v_13: Path2D;
        readonly v_2: Path2D;
        readonly v_3: Path2D;
        readonly v_4: Path2D;
        readonly v_5: Path2D;
        readonly v_6: Path2D;
        readonly v_7: Path2D;
        readonly v_8: Path2D;
        readonly v_9: Path2D;
    }>;
};
export type ICardsFactoryOptions = {
    width?: number;
    height?: number;
    borderColor?: string | CanvasGradient | CanvasPattern;
    borderRadius?: number;
    rhColor?: string | CanvasGradient | CanvasPattern | null;
    bhColor?: string | CanvasGradient | CanvasPattern | null;
    rnColor?: string | CanvasGradient | CanvasPattern | null;
    bnColor?: string | CanvasGradient | CanvasPattern | null;
    frontColor?: string | CanvasGradient | CanvasPattern;
    shirtColor?: string | CanvasGradient | CanvasPattern | null;
    fontWeight?: keyof typeof RANKS_TYPES;
};
export default function cardsFactory({ width, height, borderColor, borderRadius, rhColor, // ♥
rnColor, // ♦
bhColor, // ♠
bnColor, //  ♣
frontColor, shirtColor, fontWeight, }?: ICardsFactoryOptions): {
    basic: Readonly<{
        bha?: string;
        bhb?: string;
        bh1?: string;
        bh2?: string;
        bh3?: string;
        bh4?: string;
        bh5?: string;
        bh6?: string;
        bh7?: string;
        bh8?: string;
        bh9?: string;
        bhc?: string;
        bhd?: string;
        bna?: string;
        bnb?: string;
        bn1?: string;
        bn2?: string;
        bn3?: string;
        bn4?: string;
        bn5?: string;
        bn6?: string;
        bn7?: string;
        bn8?: string;
        bn9?: string;
        bnc?: string;
        bnd?: string;
        rha?: string;
        rhb?: string;
        rh1?: string;
        rh2?: string;
        rh3?: string;
        rh4?: string;
        rh5?: string;
        rh6?: string;
        rh7?: string;
        rh8?: string;
        rh9?: string;
        rhc?: string;
        rhd?: string;
        rna?: string;
        rnb?: string;
        rn1?: string;
        rn2?: string;
        rn3?: string;
        rn4?: string;
        rn5?: string;
        rn6?: string;
        rn7?: string;
        rn8?: string;
        rn9?: string;
        rnc?: string;
        rnd?: string;
    }>;
    chars: Readonly<{
        bhb?: string;
        bhc?: string;
        bhd?: string;
        bnb?: string;
        bnc?: string;
        bnd?: string;
        rhb?: string;
        rhc?: string;
        rhd?: string;
        rnb?: string;
        rnc?: string;
        rnd?: string;
    }>;
    other: Readonly<{
        front?: string;
        shirt?: string;
    }>;
};
