export default function cardsFactory({ width, height, bgColor, borderColor, rhColor, // ♥
rnColor, // ♦
bhColor, // ♠
bnColor, }?: {
    width?: number;
    height?: number;
    bgColor?: string | CanvasGradient | CanvasPattern;
    borderColor?: string | CanvasGradient | CanvasPattern;
    rhColor?: string | CanvasGradient | CanvasPattern | null;
    bhColor?: string | CanvasGradient | CanvasPattern | null;
    rnColor?: string | CanvasGradient | CanvasPattern | null;
    bnColor?: string | CanvasGradient | CanvasPattern | null;
}): Readonly<{
    bha: string;
    bhb: string;
    bh1: string;
    bh2: string;
    bh3: string;
    bh4: string;
    bh5: string;
    bh6: string;
    bh7: string;
    bh8: string;
    bh9: string;
    bhc: string;
    bhd: string;
    bna: string;
    bnb: string;
    bn1: string;
    bn2: string;
    bn3: string;
    bn4: string;
    bn5: string;
    bn6: string;
    bn7: string;
    bn8: string;
    bn9: string;
    bnc: string;
    bnd: string;
    rha: string;
    rhb: string;
    rh1: string;
    rh2: string;
    rh3: string;
    rh4: string;
    rh5: string;
    rh6: string;
    rh7: string;
    rh8: string;
    rh9: string;
    rhc: string;
    rhd: string;
    rna: string;
    rnb: string;
    rn1: string;
    rn2: string;
    rn3: string;
    rn4: string;
    rn5: string;
    rn6: string;
    rn7: string;
    rn8: string;
    rn9: string;
    rnc: string;
    rnd: string;
}>;
